import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import {
  COMPANY_NAME,
  ReportRow,
  ReportSummary,
} from "@/lib/report-utils";

export interface ExportOptions {
  reportTitle: string;
  dateRangeLabel: string;
  generatedBy: string;
  rows: ReportRow[];
  summary: ReportSummary;
}

function drawCompanyLogo(doc: jsPDF, x: number, y: number) {
  doc.setFillColor(37, 99, 235);
  doc.roundedRect(x, y, 14, 14, 2, 2, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("AP", x + 4.5, y + 9);
}

function formatGeneratedTime(): string {
  return new Date().toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function formatReportDate(): string {
  return new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export function exportToPdf(options: ExportOptions): void {
  const { reportTitle, dateRangeLabel, generatedBy, rows, summary } = options;
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generatedTime = formatGeneratedTime();
  const reportDate = formatReportDate();

  const addHeader = () => {
    drawCompanyLogo(doc, 14, 12);
    doc.setTextColor(17, 24, 39);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(COMPANY_NAME, 32, 18);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(107, 114, 128);
    doc.text("Attendance Management System", 32, 23);

    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.line(14, 30, pageWidth - 14, 30);

    doc.setTextColor(17, 24, 39);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(reportTitle, 14, 40);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(75, 85, 99);
    doc.text(`Report Period: ${dateRangeLabel}`, 14, 47);
    doc.text(`Report Date: ${reportDate}`, 14, 52);
    doc.text(`Generated By: ${generatedBy}`, pageWidth / 2, 47);
    doc.text(`Generated At: ${generatedTime}`, pageWidth / 2, 52);
  };

  const addSummary = (startY: number) => {
    const boxWidth = (pageWidth - 28 - 12) / 6;
    const stats = [
      { label: "Total Employees", value: String(summary.totalEmployees), color: [37, 99, 235] as [number, number, number] },
      { label: "Present", value: String(summary.present), color: [22, 163, 74] as [number, number, number] },
      { label: "Late", value: String(summary.late), color: [234, 88, 12] as [number, number, number] },
      { label: "Absent", value: String(summary.absent), color: [220, 38, 38] as [number, number, number] },
      { label: "Half Day", value: String(summary.halfDay), color: [234, 179, 8] as [number, number, number] },
      { label: "Attendance %", value: `${summary.attendancePercentage}%`, color: [79, 70, 229] as [number, number, number] },
    ];

    stats.forEach((stat, i) => {
      const x = 14 + i * (boxWidth + 2.4);
      doc.setFillColor(249, 250, 251);
      doc.setDrawColor(229, 231, 235);
      doc.roundedRect(x, startY, boxWidth, 18, 1.5, 1.5, "FD");
      doc.setFontSize(7);
      doc.setTextColor(107, 114, 128);
      doc.setFont("helvetica", "normal");
      doc.text(stat.label, x + 3, startY + 6);
      doc.setFontSize(12);
      doc.setTextColor(...stat.color);
      doc.setFont("helvetica", "bold");
      doc.text(stat.value, x + 3, startY + 14);
    });

    return startY + 24;
  };

  addHeader();
  let tableStartY = addSummary(58);

  const tableHead = [
    ["Employee ID", "Name", "Department", "Date", "Morning In", "Lunch Out", "Lunch Return", "Final Out", "Hours", "Status"],
  ];

  const tableBody = rows.map((r) => [
    r.employeeId,
    r.name,
    r.department,
    r.date,
    r.morningIn,
    r.lunchOut,
    r.lunchReturn,
    r.finalOut,
    r.workedHours,
    r.status,
  ]);

  autoTable(doc, {
    head: tableHead,
    body: tableBody.length > 0 ? tableBody : [["No records found", "", "", "", "", "", "", "", "", ""]],
    startY: tableStartY,
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
      halign: "center",
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [55, 65, 81],
      cellPadding: 2,
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 28 },
      2: { cellWidth: 24 },
      9: { halign: "center" },
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageCount = doc.getNumberOfPages();
      const currentPage = data.pageNumber;
      doc.setFontSize(8);
      doc.setTextColor(156, 163, 175);
      doc.setFont("helvetica", "normal");
      doc.text(
        `${COMPANY_NAME} — Confidential`,
        14,
        pageHeight - 8
      );
      doc.text(
        `Page ${currentPage} of ${pageCount}`,
        pageWidth - 14,
        pageHeight - 8,
        { align: "right" }
      );
    },
  });

  const safeName = reportTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`${safeName}_${new Date().toISOString().split("T")[0]}.pdf`);
}

export function exportToExcel(options: ExportOptions): void {
  const { reportTitle, dateRangeLabel, generatedBy, rows, summary } = options;
  const generatedTime = formatGeneratedTime();
  const reportDate = formatReportDate();

  const headerRows = [
    [COMPANY_NAME],
    ["Attendance Management System"],
    [],
    ["Report Title", reportTitle],
    ["Report Period", dateRangeLabel],
    ["Report Date", reportDate],
    ["Generated By", generatedBy],
    ["Generated At", generatedTime],
    [],
    ["Summary Statistics"],
    ["Total Employees", summary.totalEmployees],
    ["Present", summary.present],
    ["Late", summary.late],
    ["Absent", summary.absent],
    ["Half Day", summary.halfDay],
    ["Lunch Missing", summary.lunchMissing],
    ["Attendance Percentage", `${summary.attendancePercentage}%`],
    [],
    ["Employee ID", "Name", "Department", "Date", "Morning In", "Lunch Out", "Lunch Return", "Final Out", "Worked Hours", "Status"],
  ];

  const dataRows = rows.map((r) => [
    r.employeeId,
    r.name,
    r.department,
    r.date,
    r.morningIn,
    r.lunchOut,
    r.lunchReturn,
    r.finalOut,
    r.workedHours,
    r.status,
  ]);

  const ws = XLSX.utils.aoa_to_sheet([...headerRows, ...dataRows]);
  ws["!cols"] = [
    { wch: 14 }, { wch: 22 }, { wch: 18 }, { wch: 14 },
    { wch: 12 }, { wch: 12 }, { wch: 14 }, { wch: 12 }, { wch: 12 }, { wch: 14 },
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Report");
  const safeName = reportTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  XLSX.writeFile(wb, `${safeName}_${new Date().toISOString().split("T")[0]}.xlsx`);
}

export function printReport(options: ExportOptions): void {
  const { reportTitle, dateRangeLabel, generatedBy, rows, summary } = options;
  const generatedTime = formatGeneratedTime();
  const reportDate = formatReportDate();

  const tableRows = rows
    .map(
      (r) => `
      <tr>
        <td>${r.employeeId}</td>
        <td>${r.name}</td>
        <td>${r.department}</td>
        <td>${r.date}</td>
        <td>${r.morningIn}</td>
        <td>${r.lunchOut}</td>
        <td>${r.lunchReturn}</td>
        <td>${r.finalOut}</td>
        <td>${r.workedHours}</td>
        <td><span class="status">${r.status}</span></td>
      </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>${reportTitle}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #111827; padding: 24px; }
    .header { display: flex; align-items: center; gap: 16px; border-bottom: 2px solid #e5e7eb; padding-bottom: 16px; margin-bottom: 20px; }
    .logo { width: 48px; height: 48px; background: #2563eb; color: white; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 18px; }
    .company h1 { font-size: 22px; color: #111827; }
    .company p { font-size: 12px; color: #6b7280; }
    .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 20px; font-size: 13px; color: #4b5563; }
    .meta strong { color: #111827; }
    h2 { font-size: 18px; margin-bottom: 12px; color: #1e40af; }
    .stats { display: grid; grid-template-columns: repeat(6, 1fr); gap: 10px; margin-bottom: 24px; }
    .stat { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; text-align: center; }
    .stat .label { font-size: 10px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
    .stat .value { font-size: 20px; font-weight: bold; margin-top: 4px; }
    .stat.blue .value { color: #2563eb; }
    .stat.green .value { color: #16a34a; }
    .stat.orange .value { color: #ea580c; }
    .stat.red .value { color: #dc2626; }
    .stat.yellow .value { color: #ca8a04; }
    .stat.indigo .value { color: #4f46e5; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { background: #2563eb; color: white; padding: 8px 6px; text-align: left; font-weight: 600; }
    td { padding: 7px 6px; border-bottom: 1px solid #e5e7eb; }
    tr:nth-child(even) { background: #f9fafb; }
    .status { background: #dbeafe; color: #1e40af; padding: 2px 8px; border-radius: 9999px; font-size: 10px; font-weight: 600; }
    .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; display: flex; justify-content: space-between; }
    @media print {
      body { padding: 12px; }
      .stats { grid-template-columns: repeat(3, 1fr); }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">AP</div>
    <div class="company">
      <h1>${COMPANY_NAME}</h1>
      <p>Attendance Management System</p>
    </div>
  </div>
  <h2>${reportTitle}</h2>
  <div class="meta">
    <div><strong>Report Period:</strong> ${dateRangeLabel}</div>
    <div><strong>Report Date:</strong> ${reportDate}</div>
    <div><strong>Generated By:</strong> ${generatedBy}</div>
    <div><strong>Generated At:</strong> ${generatedTime}</div>
  </div>
  <div class="stats">
    <div class="stat blue"><div class="label">Total Employees</div><div class="value">${summary.totalEmployees}</div></div>
    <div class="stat green"><div class="label">Present</div><div class="value">${summary.present}</div></div>
    <div class="stat orange"><div class="label">Late</div><div class="value">${summary.late}</div></div>
    <div class="stat red"><div class="label">Absent</div><div class="value">${summary.absent}</div></div>
    <div class="stat yellow"><div class="label">Half Day</div><div class="value">${summary.halfDay}</div></div>
    <div class="stat indigo"><div class="label">Attendance %</div><div class="value">${summary.attendancePercentage}%</div></div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Employee ID</th><th>Name</th><th>Department</th><th>Date</th>
        <th>Morning In</th><th>Lunch Out</th><th>Lunch Return</th><th>Final Out</th>
        <th>Hours</th><th>Status</th>
      </tr>
    </thead>
    <tbody>${tableRows || '<tr><td colspan="10" style="text-align:center;padding:20px;color:#9ca3af;">No records found</td></tr>'}</tbody>
  </table>
  <div class="footer">
    <span>${COMPANY_NAME} — Confidential</span>
    <span>Printed on ${generatedTime}</span>
  </div>
  <script>window.onload = () => { window.print(); window.onafterprint = () => window.close(); };</script>
</body>
</html>`;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
  }
}
